version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
